# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.TextField(blank=True),
        ),
    ]
